use yumcoach_db;

CREATE TABLE IF NOT EXISTS `meal_history` (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
    created_date DATETIME NOT NULL DEFAULT NOW(),
    date DATETIME NOT NULL DEFAULT NOW(),
    type VARCHAR(30) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `meal` (
	id INT AUTO_INCREMENT PRIMARY KEY,
    history_id INT NOT NULL,
	meal_code VARCHAR(255) NOT NULL,
	meal_name VARCHAR(255) NOT NULL,
    amount INT,
    kcal DECIMAL(10, 2) DEFAULT 0,
    protein DECIMAL(10, 2) DEFAULT 0,
    carbs DECIMAL(10, 2) DEFAULT 0,
    fat DECIMAL(10, 2) DEFAULT 0,
	FOREIGN KEY (history_id) REFERENCES meal_history(id) ON DELETE CASCADE
);

